// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nabyudcfhkdyfhrvfelc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5hYnl1ZGNmaGtkeWZocnZmZWxjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1NjE4NDQsImV4cCI6MjA3MTEzNzg0NH0.nBYbmWT9snaDOa2fLkdjVC4JeaRww_rourKib63TnwM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});